spring:
  application:
    name: wolf-account
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: false
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/wolf_account?useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: study.daydayup.wolf.business.account.biz.dal.dataobject
  mapper-locations: classpath*:mapper/*.xml, classpath*:mapper/auto/*.xml

wolf:
  sms:
    signature: "onion"
    senderNum: "ONION"
    suppler:
      skyline:
        appId: "cs_3wegkt"
        appSecret: "dwhg27jN"
        sendUrl: "http://sms.skylinelabs.cc:20003/"

dubbo:
  scan:
    base-packages: study.daydayup.wolf.business.account
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://localhost
  application:
    qos-enable: false
