spring:
    application:
        name: account
    profiles:
        active: @profileActive@
    main:
        banner-mode: "off"
        allow-bean-definition-overriding: true
    devtools:
        restart:
            enabled: false
    jackson:
            date-format: "yyyy-MM-dd HH:mm:ss"
            time-zone: GMT+8

mybatis:
    type-aliases-package: com.meizizi.doraemon.account.biz.dal.dataobject
    mapper-locations: classpath*:mapper/*.xml

eureka:
    instance:
        prefer-ip-address: true
        instance-id: @project.artifactId@:${spring.cloud.client.ip-address}:${server.port}

