"estar.goods"                         : [1, ],
"estar.goods.add"                     : [2, ""],
"estar.goods.modify"                  : [3, ""],
"estar.goods.delete"                  : [4, ""],
"estar.goods.query"                   : [5, ""],
"estar.goods.listing"                 : [6, ""],


"estar.trade"                         : [10, ],
"estar.trade.send"                    : [11, ""],
"estar.trade.close"                   : [11, ""],



"estar.dashboard"                     : [30, ""],


"estar.setting"                       : [40, ""],

