spring:
  cloud:
    nacos:
      discovery:
        register-enabled: false
        enabled: true
        server-addr: 127.0.0.1:8848

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    register: false
  cloud:
    subscribed-services: ${provider.application.name}
  application:
    qos-enable: false

provider:
  application:
    name: wolf-union

wolf:
  auth:
    enable: true
  sdk:
    aliyun:
      oss:
        accessId: LTAI4Fc6aira5zSQ8A1EknvR
        accessKey: 4N1c2jMCclrf5AhSSLMY7mGCkmJeNN
        endPoint: oss-ap-south-1.aliyuncs.com
        defaultBucket: onionwallet-private
        rootPath: img/