spring:
  shardingsphere:
    datasource:
      names: account, goods, trade, pay, mq
      account:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_account?useSSL=false
      goods:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_goods?useSSL=false
      trade:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_trade?useSSL=false
      pay:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_pay?useSSL=false
      mq:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_mq?useSSL=false
    sharding:
      tables:
        #account
        access_token.actual-data-nodes: account.access_token
        account.actual-data-nodes: account.account
        account_alipay.actual-data-nodes: account.account_alipay
        account_wechat.actual-data-nodes: account.account_wechat
        organiztion.actual-data-nodes: account.organiztion
        verify_code.actual-data-nodes: account.verify_code
        #goods
        goods.actual-data-nodes: goods.goods
        goods_detail.actual-data-nodes: goods.goods_detail
        goods_loan.actual-data-nodes: goods.goods_loan
        goods_installment.actual-data-nodes: goods.goods_installment
        sku.actual-data-nodes: goods.sku
        #trade
        assurance_term.actual-data-nodes: trade.assurance_term
        consign_term.actual-data-nodes: trade.consign_term
        contract.actual-data-nodes: trade.contract
        contract_state_log.actual-data-nodes: trade.contract_state_log
        installment_term.actual-data-nodes: trade.installment_term
        objects_term.actual-data-nodes: trade.objects_term
        order.actual-data-nodes: trade.order
        order_address.actual-data-nodes: trade.order_address
        order_line.actual-data-nodes: trade.order_line
        order_state_log.actual-data-nodes: trade.order_state_log
        payment_term.actual-data-nodes: trade.payment_term
        price_change_log.actual-data-nodes: trade.price_change_log
        repayment_term.actual-data-nodes: trade.repayment_term
        trade_memo.actual-data-nodes: trade.trade_memo
        #mq
        wmq_message.actual-data-nodes: mq.wmq_message
        wmq_queue.actual-data-nodes: mq.wmq_queue
        wmq_scheduled_message.actual-data-nodes: mq.wmq_scheduled_message
        wmq_task.actual-data-nodes: mq.wmq_task
        wmq_tcc_message.actual-data-nodes: mq.wmq_tcc_message

logging:
  level:
    root: info
