spring:
  application:
    name: wolf-union
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true


mybatis:
  mapper-locations: classpath*:mapper/*.xml, classpath*:mapper/auto/*.xml
  type-aliases-package: study.daydayup.wolf.business.*.dal.dataobject

pagehelper:
  support-methods-arguments: true
  reasonable: true
  helper-dialect: mysql

dubbo:
  scan:
    base-packages: study.daydayup.wolf.business
  protocols:
    dubbo:
      name: dubbo
      port: 9080
  registry:
    address: spring-cloud://localhost
  application:
    qos-enable: false


