spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
  shardingsphere:
    datasource:
      names: account, goods, trade, pay, mq, setting
      account:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_account?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      goods:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_goods?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      trade:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_trade?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      pay:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_pay?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      mq:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_mq?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      setting:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_setting?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
    sharding:
      tables:
        #account
        access_token.actual-data-nodes: account.access_token
        account.actual-data-nodes: account.account
        account_alipay.actual-data-nodes: account.account_alipay
        account_wechat.actual-data-nodes: account.account_wechat
        organiztion.actual-data-nodes: account.organiztion
        verify_code.actual-data-nodes: account.verify_code
        #goods
        goods.actual-data-nodes: goods.goods
        goods_detail.actual-data-nodes: goods.goods_detail
        goods_loan.actual-data-nodes: goods.goods_loan
        goods_installment.actual-data-nodes: goods.goods_installment
        sku.actual-data-nodes: goods.sku
        #trade
        assurance_term.actual-data-nodes: trade.assurance_term
        consign_term.actual-data-nodes: trade.consign_term
        contract.actual-data-nodes: trade.contract
        trade_state_log.actual-data-nodes: trade.trade_state_log
        installment_term.actual-data-nodes: trade.installment_term
        loan_term.actual-data-nodes: trade.loan_term
        objects_term.actual-data-nodes: trade.objects_term
        order.actual-data-nodes: trade.order
        order_address.actual-data-nodes: trade.order_address
        order_line.actual-data-nodes: trade.order_line
        order_state_log.actual-data-nodes: trade.order_state_log
        payment_term.actual-data-nodes: trade.payment_term
        price_change_log.actual-data-nodes: trade.price_change_log
        repayment_term.actual-data-nodes: trade.repayment_term
        trade_memo.actual-data-nodes: trade.trade_memo
        #mq
        wmq_message.actual-data-nodes: mq.wmq_message
        wmq_queue.actual-data-nodes: mq.wmq_queue
        wmq_scheduled_message.actual-data-nodes: mq.wmq_scheduled_message
        wmq_task.actual-data-nodes: mq.wmq_task
        wmq_tcc_message.actual-data-nodes: mq.wmq_tcc_message
        #setting
        account_status.actual-data-nodes: setting.account_status
        customer_status.actual-data-nodes: setting.customer_status
    props:
      sql:
        show: true

dubbo:
  scan:
    base-packages: study.daydayup.wolf.business
  protocols:
    dubbo:
      anyhost: true
      host: 127.0.0.1
      name: dubbo
      port: 9080
  registry:
    address: nacos://127.0.0.1:8848
  application:
    qos-enable: false
  cloud:
    subscribed-services: ""
  provider:
    filter:


logging:
  level:
    root: info
