spring:
  application:
    name: hello-consumer
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: ${provider.application.name}
  application:
    qos-enable: false

server:
  port: 8081

provider:
  application:
    name: hello-provider