spring:
  application:
    name: wolf-mq
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/wolf_mq?useSSL=falseuseUnicode=true&characterEncoding=utf8mb4
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: study.daydayup.wolf.mq.broker.dal.dataobject
  mapper-locations: classpath:sqlmap/*.xml, sqlmap/auto/*.xml

dubbo:
  scan:
    base-packages: study.daydayup.wolf.mq.broker
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://localhost
  application:
    qos-enable: false
