spring:
  cloud:
    nacos:
      discovery:
        register-enabled: true
        enabled: true
        server-addr: 127.0.0.1:8848

dubbo:
  registry:
    address: spring-cloud://localhost
    register: false
  cloud:
    subscribed-services: ${provider.application.name}
  application:
    qos-enable: false

wolf:
  auth:
    enable: true
    excludedPaths: "/auth/**/*,/pay/*/subscribe"
  sdk:
    aliyun:
      oss:
        accessId: LTAI4Fc6aira5zSQ8A1EknvR
        accessKey: 4N1c2jMCclrf5AhSSLMY7mGCkmJeNN
        endPoint: oss-ap-south-1.aliyuncs.com
        defaultBucket: onionwallet-private
        rootPath: img/

