spring:
  application:
    name: wolf-union-app
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0

management:
  endpoints:
    web:
      exposure:
        include : "*"





server:
  port: 8100

provider:
  application:
    name: wolf-union


