spring:
  application:
    name: hello-sharding
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: learn, account
      learn:
        username: root
        password: 123456
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/learn?useSSL=false
      account:
        username: root
        password: 123456
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/account?useSSL=false
      sharding:
        tables:
          account:
            actual-data-nodes: account.account
          tag:
            actual-data-nodes: learn.account
        props:
          sql.show: true
server:
  port:8090

