spring:
  application:
    name: hello-sharding
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: learn, account
      learn:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/learn?useSSL=false
      account:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_account?useSSL=false
    sharding:
      tables:
        tag:
          actual-data-nodes: learn.tag
        account:
          actual-data-nodes: account.account

server:
  port: 8095

