spring:
  cloud:
    nacos:
      discovery:
        register-enabled: true
        enabled: true
        server-addr: 127.0.0.1:8848

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  cloud:
    subscribed-services: ${provider.application.name}
  application:
    qos-enable: false

provider:
  application:
    name: wolf-union

