spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
  shardingsphere:
    datasource:
      names: account, goods, trade, pay, mq, setting, credit, onion, datav, org
      account:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_account?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      goods:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_goods?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      trade:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_trade?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      pay:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_pay?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      mq:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_mq?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      setting:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_setting?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      credit:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_credit?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      datav:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_datav?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      onion:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/onion?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
      org:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/wolf_org?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true


    props:
      sql:
        show: true

dubbo:
  scan:
    base-packages: study.daydayup.wolf.business
  protocols:
    dubbo:
      anyhost: true
      host: 127.0.0.1
      name: dubbo
      port: 9080
  registry:
    address: nacos://127.0.0.1:8848
  application:
    qos-enable: false
  cloud:
    subscribed-services: ""

pay:
  razorpay:
    keyId: "rzp_test_AVfB2VIxmnf4v6"
    keySecret: "pJ8TpvIge88kfBBrAPurUP7p"
    webHookSecret: "T2kdT6vwgBcPDY7Qc8"


logging:
  level:
    root: info
